project_id = "euocvkvdixpxfznrduzi"

[functions]
  [functions.ai-assistant]
    verify_jwt = false
  [functions.ai-event-mapper]
    verify_jwt = false
  [functions.ai-tracking-setup]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.email-tracking]
    verify_jwt = false
  [functions.execute-workflow]
    verify_jwt = false
  [functions.generate-email-content]
    verify_jwt = false
  [functions.generate-workflow]
    verify_jwt = false
  [functions.payment-gateway]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.public-api]
    verify_jwt = false
  [functions.send-email-campaign]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.process-tracking-queue]
    verify_jwt = false
  [functions.track-event]
    verify_jwt = false
  [functions.serve-ghost-script]
    verify_jwt = false
  [functions.track-event-alias]
    verify_jwt = false
