project_id = "euocvkvdixpxfznrduzi"

[functions.generate-workflow]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = false

[functions.payment-gateway]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.send-email-campaign]
verify_jwt = false

[functions.email-tracking]
verify_jwt = false

[functions.generate-email-content]
verify_jwt = false

[functions.ai-tracking-setup]
verify_jwt = false

[functions.ai-event-mapper]
verify_jwt = false